services:
  personal-site:
    platform: linux/arm64
    build:
      context: ..
      dockerfile: deployment/Dockerfile
      args:
        VERSION: ${VERSION:-latest}
        SHA: ${SHA:-unknown}
      tags: # not allowed in compose version '3', so override here
        - ${REGISTRY:-unknown}/personal-site:${VERSION:-latest}
        - ${REGISTRY:-unknown}/personal-site:${SHA:-unknown}
