version: "3.8"

services:
  personal-site:
    image: ${REGISTRY:-localhost:5000}/personal-site:${VERSION:-latest}
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first
      labels:
        - "traefik.enable=true"
        - "traefik.http.services.personal-site.loadbalancer.server.port=1960" # internal port for traefik<>service
        - "traefik.http.routers.personal-site.rule=HostRegexp(`^(www\\.)?oliverlambson\\.com(\\.localhost)?$$`)"
        - "traefik.http.routers.personal-site.entrypoints=web" # 'web' defined in traefik config
        # TODO: https
        # - "traefik.http.routers.personal-site.entrypoints=websecure" # 'websecure' defined in traefik config
        # - "traefik.http.routers.personal-site.tls.certresolver=letsencrypt"
        # middleware for redirecting to www, with redirectregex to enforce www
        # - "traefik.http.routers.personal-site.middlewares=redirect-to-www"
        # - "traefik.http.middlewares.redirect-to-www.redirectregex.regex=^https?://(?:www\\.)?(.+)"
        # - "traefik.http.middlewares.redirect-to-www.redirectregex.replacement=https://www.$${1}"
        # - "traefik.http.middlewares.redirect-to-www.redirectregex.permanent=true"
    networks:
      - public
      - loki

networks:
  public:
    external: true
  loki:
    external: true
