version: "3.8"

services:
  personal-site:
    image: ${REGISTRY:-localhost:5000}/personal-site:${VERSION:-latest}
    environment:
      _deploy: "0"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first
      labels:
        - "traefik.enable=true"
        - "traefik.http.services.personal-site.loadbalancer.server.port=1960"
        - "traefik.http.routers.personal-site.rule=Host(`oliverlambson.com`) ||
          Host(`www.oliverlambson.com`) ||
          HostRegexp(`^(www\\.)?oliverlambson(\\..+)?$`)"
        - "traefik.http.routers.personal-site.entrypoints=websecure"
        - "traefik.http.routers.personal-site.tls.certresolver=letsencrypt"
        # middleware for redirecting to www, with redirectregex to enforce www
        - "traefik.http.middlewares.redirect-to-www.redirectregex.regex=^https?://(?:www\\.)?(.+)"
        - "traefik.http.middlewares.redirect-to-www.redirectregex.replacement=https://www.$${1}"
        - "traefik.http.middlewares.redirect-to-www.redirectregex.permanent=true"
        - "traefik.http.routers.personal-site.middlewares=redirect-to-www"
    networks:
      - public

networks:
  public:
    external: true
