name: build:personal-site

on:
  release:
    types:
      - published
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - id: vars
        run: |
          sha_short="$(git rev-parse --short HEAD)"
          echo "sha_short=$sha_short" >>$GITHUB_OUTPUT

          echo "tags<<EOF" >>$GITHUB_OUTPUT
          echo "$REGISTRY_HOST/personal-site:$sha_short" >>$GITHUB_OUTPUT
          if [ "${{ github.event_name }}" = "release" ]; then
            echo "$REGISTRY_HOST/personal-site:${{ github.ref_name }}" >>$GITHUB_OUTPUT
          fi
          echo "EOF" >>$GITHUB_OUTPUT
        env:
          REGISTRY_HOST: ${{ vars.DOCKER_REGISTRY_HOST }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to registry
        uses: docker/login-action@v3
        with:
          registry: ${{ vars.DOCKER_REGISTRY_HOST }}
          username: ${{ secrets.DOCKER_REGISTRY_USER }}
          password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: deployment/Dockerfile
          push: true
          tags: ${{ steps.vars.outputs.tags }}
          build-args: |
            VERSION="${{ github.ref_name }}"
            SHA="${{ steps.vars.outputs.sha_short }}"
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/arm64
