name: deploy:personal-site

on:
  push:
    branches:
      - main
    paths:
      - "deployment/**"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Deploy Stack
        uses: oliverlambson/personal.gitops/.github/actions/deploy-stack@cd-v1
        with:
          name: personal-site
          directory: deployment
          ssh-user: ${{ secrets.VPS_SSH_USER }}
          ssh-host: ${{ secrets.VPS_SSH_HOST }}
          ssh-private-key: ${{ secrets.VPS_SSH_KEY }}
